### ISSUE TITLE
[bug] : 첨부파일 업로드/다운로드 경로가 프로젝트 내에 존재하여  war 파일로 배포 시, 접근을 못해 NullPointerException 발생

### ISSUE THREAD

**Issue by rlawns0327** [DEU-WebMail-System/WebMail-System#23]
## 📝 Description
첨부파일이 프로젝트 내부에 저장되어 war로 배포 시, 접근이 안되어 오류 발생

1. 전송 시, 전송 실패 오류 발생

2. 메일을 읽으면 해당 오류 발생
![image](https://github.com/DEU-WebMail-System/WebMail-System/assets/30451538/d369e9d4-00dd-4c1f-9e5d-0ebf694430ea)

## 📍 Todo
- [x]  프로젝트 내부에 저장되는 로직을 외부에서 저장되도록 변경하고 외부 폴더에서 읽어오는 환경으로 변경
- [x] upload 경로 변경
- [x] download 경로 변경
- [x] 현재는 로컬 PC 환경 경로에 저장되므로 버그 fix 후 서버 pc의 경로로 변경

## 📢 To Reviewers
🔗 Reference
