### ISSUE TITLE
[CI] 무중단 배포 환경 구성

### ISSUE THREAD

**Issue by rlawns0327** [DEU-WebMail-System/WebMail-System#5]
## 📝 Description
설명을 작성하세요.

## 📍 Todo
- [x]  nginx/springboot 환경 구성
- [x]  포트 관리용 properties 파일 작성
- [x]  무중단 배포를 위한 shell script  작성
- [x]  health check를 위한 controller 코드 생성
- [x]  github action에 스크립트 실행 코드를 추가하여 자동화

## 📢 To Reviewers
🔗 Reference
